# Where should we write the GIF?
Output ../startup.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 18
Set Width 1920
Set Height 1080

Type "relay"

Enter

Sleep 100ms

Type "a"

Sleep 200ms

Type "New Collection"

Enter

Sleep 200ms

Enter

Sleep 200ms

Type "a"

Type "New Endpoint"

Enter

Sleep 200ms

Enter

Sleep 200ms

Ctrl+l

Type "https://jsonplaceholder.typicode.com/users"

Ctrl+S

Ctrl+r

Sleep 500ms

Ctrl+d

Sleep 50ms

Ctrl+d

Sleep 50ms

Ctrl+d

Sleep 50ms

Enter

Sleep 2

